[package]
name = "simple-auth-server"
version = "0.1.0"
authors = ["Edmund Goller <matrim.eg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.4"
actix-web = "0.7.8"
bcrypt = "0.2.0"
chrono = {version = "0.4.6", features=["serde"]}
diesel = {version="1.4.6", features=["postgres", "uuid", "r2d2", "chrono"]}
dotenv = "0.13.0"
env_logger = "0.5.13"
failure = "0.1.2"
frank_jwt="3.0"
futures="0.1"
jsonwebtoken="5.0.1"
r2d2 = "0.8.2"
serde_derive="1.0.79"
serde_json="1.0"
serde="1.0"
sparkpost = "0.4"
uuid = {version="0.6.5", features = ["serde", "v4"]}